service: serverless-hexagonal-template

plugins:
  - serverless-iam-roles-per-function
  - serverless-export-env

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  profile: ${self:custom.deployment.profile.${self:provider.stage}}
  region: ${self:custom.deployment.region.${self:provider.stage}}
  lambdaHashingVersion: 20201221
  logRetentionInDays: 60 # how long logs are kept in CloudWatch
  environment:
    stage: ${self:provider.stage}
    region: ${self:provider.region}
    httpApiGatewayEndpointId: !Ref HttpApi
  tags:
    Application: ${self:service}
    Stage: ${self:provider.stage}

useDotenv: false
configValidationMode: off

custom:
  deployment: ${file(config/deployment.yml):deployment}
  description: Your short project description that will be shown in Lambda -> Applications console & in CloudFormation stack

functions:
  createItem:
    handler: src/createItem/function.handler
    description: Create Item in repository
    memorySize: 128
    timeout: 5
    environment:
      foo: bar
    events:
      - httpApi:
          method: POST
          path: /item

  processItem:
    handler: src/processItem/function.handler
    description: Triggered by DynamoDB Streams. Does some work on newly created Item
    memorySize: 128
    timeout: 5
    environment:
      message: Hello World!

package:
  exclude:
    - __tests__/**
    - config/**
    - documentation/**
    - '*'

resources:
  Description: ${self:custom.description}