deployment:
  profile: # references you profiles set in ~/.aws/credentials
    dev: default
    test: default
    prod: default
  region:
    dev: eu-central-1   # Frankfurt
    test: eu-west-1     # Ireland
    prod: us-east-1     # N.Virginia